### ISSUE TITLE
Suggestion: replace BootStrapVerticle with vertx-boot

### ISSUE THREAD

**Issue by jponge** [aws-samples/reactive-refarch-cloudformation#1]
Hi,

The BootStrapVerticle that you are using at https://github.com/aws-samples/reactive-refarch-cloudformation/blob/master/services/tracking-service/reactive-vertx/src/main/java/com/amazon/BootStrapVerticle.java does a very fine job, albeit it does not report failures. Indeed when one of your verticles fails to deploy for some reason, a sensible behavior is to propagate the failure to the verticle that tried deploying it in a `start` method.

That logic + the boilerplate of deploying verticles may be simplified with https://github.com/jponge/vertx-boot

This is _just_ a suggestion of course 😉

**Comment by smoell** [comment]
Hi,

oh thank you, I'll take a look!

**Comment by jponge** [comment]
Note that I need to make a new release at some point ;-)

**Comment by smoell** [comment]
I've implemented failure handling with a few additional lines of code, will push changes in the next release, thx for contributing!

**Comment by jponge** [comment]
@smoell Note that I've just released vertx-boot 0.0.2
