### ISSUE TITLE
Presentation Video?

### ISSUE THREAD

**Issue by bmsantos** [aws-samples/reactive-refarch-cloudformation#3]
@smoell, I'm interested in exploring a similar solution for a project and I was wondering if there is a presentation video for this?

I noticed that there are some slides made for AWS Summit but haven't been able to find any presentation video.

Cheers,
B.

**Comment by smoell** [comment]
Hi Bruno,

unfortunately, the session was not recorded, only the slides are available.

Regards,
Sascha
